user_input1 = int(input("enter a number: "))
user_input2 = int(input("enter a number: "))
user_input3 = int(input("enter a number: "))
user_input4 = int(input("enter a number: "))
print(user_input1 + user_input2 + user_input3 + user_input4)
print(user_input1 - user_input2 - user_input3 - user_input4)
print(user_input1 // user_input2 // user_input3 // user_input4)
print(user_input1 ** user_input2 ** user_input3 ** user_input4)
